NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.custom-authorities.coffee-export.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.custom-authorities.coffee-export.com-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca.custom-authorities.coffee-export.com-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca.custom-authorities.coffee-export.com-cert.pem
    OrganizationalUnitIdentifier: orderer
